# This file contains the configuration for the Corsair RGB keyboard. It is used to map the keys to the LED IDs on the keyboard.
# In this example, the keys are mapped to the LED IDs for the Corsair Strafe RGB keyboard (UK Layout). You can modify this mapping to match your keyboard.
# Valid key names can be found in the CorsairLedId_Keyboard enum at https://github.com/CorsairOfficial/cue-sdk-python/blob/master/src/cuesdk/enums.py.

from cuesdk import CorsairLedId_Keyboard

# Define the width and height of the keyboard, this may change if you have G keys etc.
KEYBOARD_WIDTH = 21
KEYBOARD_HEIGHT = 6

# Define the maximum number of retries to connect to the Corsair iCUE software
MAX_RETRIES = 5

# Precompute the mapping of keys to LED IDs on the keyboard
def precompute_led_mapping():
    # These mappings assume a grid layout for the keyboard, with each row having an equal number of keys. For blank space with no keys, the LED ID is set to Invalid.
    key_to_led_id = {
    (0, 0): CorsairLedId_Keyboard.CLK_Escape,
    (1, 0): CorsairLedId_Keyboard.CLK_F1,
    (2, 0): CorsairLedId_Keyboard.CLK_F2,
    (3, 0): CorsairLedId_Keyboard.CLK_F3,
    (4, 0): CorsairLedId_Keyboard.CLK_F4,
    (5, 0): CorsairLedId_Keyboard.CLK_F5,
    (6, 0): CorsairLedId_Keyboard.CLK_F6,
    (7, 0): CorsairLedId_Keyboard.CLK_F7,
    (8, 0): CorsairLedId_Keyboard.CLK_F8,
    (9, 0): CorsairLedId_Keyboard.CLK_F9,
    (10, 0): CorsairLedId_Keyboard.CLK_F10,
    (11, 0): CorsairLedId_Keyboard.CLK_F11,
    (12, 0): CorsairLedId_Keyboard.CLK_F12,
    (13, 0): CorsairLedId_Keyboard.CLK_PrintScreen,
    (14, 0): CorsairLedId_Keyboard.CLK_ScrollLock,
    (15, 0): CorsairLedId_Keyboard.CLK_PauseBreak,
    # For now these are set to Invalid, which doesn't exist on my keyboard as there are no keys in this position
    (16, 0): CorsairLedId_Keyboard.CLK_Invalid,
    (17, 0): CorsairLedId_Keyboard.CLK_Invalid,
    (18, 0): CorsairLedId_Keyboard.CLK_Invalid,
    (19, 0): CorsairLedId_Keyboard.CLK_Invalid,
    (20, 0): CorsairLedId_Keyboard.CLK_Invalid,

    (0, 1): CorsairLedId_Keyboard.CLK_GraveAccentAndTilde,
    (1, 1): CorsairLedId_Keyboard.CLK_1,
    (2, 1): CorsairLedId_Keyboard.CLK_2,
    (3, 1): CorsairLedId_Keyboard.CLK_3,
    (4, 1): CorsairLedId_Keyboard.CLK_4,
    (5, 1): CorsairLedId_Keyboard.CLK_5,
    (6, 1): CorsairLedId_Keyboard.CLK_6,
    (7, 1): CorsairLedId_Keyboard.CLK_7,
    (8, 1): CorsairLedId_Keyboard.CLK_8,
    (9, 1): CorsairLedId_Keyboard.CLK_9,
    (10, 1): CorsairLedId_Keyboard.CLK_0,
    (11, 1): CorsairLedId_Keyboard.CLK_MinusAndUnderscore,
    (12, 1): CorsairLedId_Keyboard.CLK_EqualsAndPlus,
    (13, 1): CorsairLedId_Keyboard.CLK_Backspace,
    (14, 1): CorsairLedId_Keyboard.CLK_Insert,
    (15, 1): CorsairLedId_Keyboard.CLK_Home,
    (16, 1): CorsairLedId_Keyboard.CLK_PageUp,
    (17, 1): CorsairLedId_Keyboard.CLK_NumLock,
    (18, 1): CorsairLedId_Keyboard.CLK_KeypadSlash,
    (19, 1): CorsairLedId_Keyboard.CLK_KeypadAsterisk,
    (20, 1): CorsairLedId_Keyboard.CLK_KeypadMinus,

    (0, 2): CorsairLedId_Keyboard.CLK_Tab,
    (1, 2): CorsairLedId_Keyboard.CLK_Q,
    (2, 2): CorsairLedId_Keyboard.CLK_W,
    (3, 2): CorsairLedId_Keyboard.CLK_E,
    (4, 2): CorsairLedId_Keyboard.CLK_R,
    (5, 2): CorsairLedId_Keyboard.CLK_T,
    (6, 2): CorsairLedId_Keyboard.CLK_Y,
    (7, 2): CorsairLedId_Keyboard.CLK_U,
    (8, 2): CorsairLedId_Keyboard.CLK_I,
    (9, 2): CorsairLedId_Keyboard.CLK_O,
    (10, 2): CorsairLedId_Keyboard.CLK_P,
    (11, 2): CorsairLedId_Keyboard.CLK_BracketLeft,
    (12, 2): CorsairLedId_Keyboard.CLK_BracketRight,
    (13, 2): CorsairLedId_Keyboard.CLK_Enter,
    (14, 2): CorsairLedId_Keyboard.CLK_Delete,
    (15, 2): CorsairLedId_Keyboard.CLK_End,
    (16, 2): CorsairLedId_Keyboard.CLK_PageDown,
    (17, 2): CorsairLedId_Keyboard.CLK_Keypad7,
    (18, 2): CorsairLedId_Keyboard.CLK_Keypad8,
    (19, 2): CorsairLedId_Keyboard.CLK_Keypad9,
    (20, 2): CorsairLedId_Keyboard.CLK_KeypadPlus,

    (0, 3): CorsairLedId_Keyboard.CLK_CapsLock,
    (1, 3): CorsairLedId_Keyboard.CLK_A,
    (2, 3): CorsairLedId_Keyboard.CLK_S,
    (3, 3): CorsairLedId_Keyboard.CLK_D,
    (4, 3): CorsairLedId_Keyboard.CLK_F,
    (5, 3): CorsairLedId_Keyboard.CLK_G,
    (6, 3): CorsairLedId_Keyboard.CLK_H,
    (7, 3): CorsairLedId_Keyboard.CLK_J,
    (8, 3): CorsairLedId_Keyboard.CLK_K,
    (9, 3): CorsairLedId_Keyboard.CLK_L,
    (10, 3): CorsairLedId_Keyboard.CLK_SemicolonAndColon,
    (11, 3): CorsairLedId_Keyboard.CLK_ApostropheAndDoubleQuote,
    (12, 3): CorsairLedId_Keyboard.CLK_NonUsTilde,
    (13, 3): CorsairLedId_Keyboard.CLK_Invalid,
    (14, 3): CorsairLedId_Keyboard.CLK_Invalid,
    (15, 3): CorsairLedId_Keyboard.CLK_Invalid,
    (16, 3): CorsairLedId_Keyboard.CLK_Invalid,
    (17, 3): CorsairLedId_Keyboard.CLK_Keypad4,
    (18, 3): CorsairLedId_Keyboard.CLK_Keypad5,
    (19, 3): CorsairLedId_Keyboard.CLK_Keypad6,
    (20, 3): CorsairLedId_Keyboard.CLK_Invalid,

    (0, 4): CorsairLedId_Keyboard.CLK_LeftShift,
    (1, 4): CorsairLedId_Keyboard.CLK_NonUsBackslash,
    (2, 4): CorsairLedId_Keyboard.CLK_Z,
    (3, 4): CorsairLedId_Keyboard.CLK_X,
    (4, 4): CorsairLedId_Keyboard.CLK_C,
    (5, 4): CorsairLedId_Keyboard.CLK_V,
    (6, 4): CorsairLedId_Keyboard.CLK_B,
    (7, 4): CorsairLedId_Keyboard.CLK_N,
    (8, 4): CorsairLedId_Keyboard.CLK_M,
    (9, 4): CorsairLedId_Keyboard.CLK_CommaAndLessThan,
    (10, 4): CorsairLedId_Keyboard.CLK_PeriodAndBiggerThan,
    (11, 4): CorsairLedId_Keyboard.CLK_SlashAndQuestionMark,
    (12, 4): CorsairLedId_Keyboard.CLK_RightShift,
    (13, 4): CorsairLedId_Keyboard.CLK_Invalid,
    (14, 4): CorsairLedId_Keyboard.CLK_Invalid,
    (15, 4): CorsairLedId_Keyboard.CLK_UpArrow,
    (16, 4): CorsairLedId_Keyboard.CLK_Invalid,
    (17, 4): CorsairLedId_Keyboard.CLK_Keypad1,
    (18, 4): CorsairLedId_Keyboard.CLK_Keypad2,
    (19, 4): CorsairLedId_Keyboard.CLK_Keypad3,
    (20, 4): CorsairLedId_Keyboard.CLK_KeypadEnter,

    (0, 5): CorsairLedId_Keyboard.CLK_LeftCtrl,
    (1, 5): CorsairLedId_Keyboard.CLK_LeftGui,
    (2, 5): CorsairLedId_Keyboard.CLK_LeftAlt,
    (3, 5): CorsairLedId_Keyboard.CLK_Invalid,
    (4, 5): CorsairLedId_Keyboard.CLK_Invalid,
    (5, 5): CorsairLedId_Keyboard.CLK_Invalid,
    (6, 5): CorsairLedId_Keyboard.CLK_Space,
    (7, 5): CorsairLedId_Keyboard.CLK_Invalid,
    (8, 5): CorsairLedId_Keyboard.CLK_Invalid,
    (9, 5): CorsairLedId_Keyboard.CLK_Invalid,
    (10, 5): CorsairLedId_Keyboard.CLK_RightAlt,
    (11, 5): CorsairLedId_Keyboard.CLK_RightGui,
    (12, 5): CorsairLedId_Keyboard.CLK_Application,
    (13, 5): CorsairLedId_Keyboard.CLK_RightCtrl,
    (14, 5): CorsairLedId_Keyboard.CLK_LeftArrow,
    (15, 5): CorsairLedId_Keyboard.CLK_DownArrow,
    (16, 5): CorsairLedId_Keyboard.CLK_RightArrow,
    (17, 5): CorsairLedId_Keyboard.CLK_Keypad0,
    (18, 5): CorsairLedId_Keyboard.CLK_Invalid,
    (19, 5): CorsairLedId_Keyboard.CLK_KeypadPeriodAndDelete,
    (20, 5): CorsairLedId_Keyboard.CLK_Invalid,
    }

    return key_to_led_id
